-- RoomBooking schema + seed
-- Works on Supabase Postgres (or any PostgreSQL 13+)

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('Admin', 'Employee')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS rooms (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  meeting_name TEXT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_booking_time_order CHECK (start_time < end_time)
);

CREATE INDEX IF NOT EXISTS idx_bookings_room_date_status ON bookings(room_id, date, status);
CREATE INDEX IF NOT EXISTS idx_bookings_user_created ON bookings(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_created ON bookings(created_at DESC);

CREATE TABLE IF NOT EXISTS registration_requests (
  id BIGSERIAL PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NULL,
  reason TEXT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_registration_requests_status_created
  ON registration_requests(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_registration_requests_email
  ON registration_requests(email);

-- Add password_hash column if upgrading an existing database
ALTER TABLE registration_requests ADD COLUMN IF NOT EXISTS password_hash TEXT NULL;

-- Seed permanent first admin (idempotent).
-- IMPORTANT: The password_hash below is a bcrypt hash generated by Node.js (bcrypt npm package).
-- Do NOT use pgcrypto's crypt() here — it produces $2a$ hashes that Node bcrypt cannot verify.
-- To regenerate: node -e "import('bcrypt').then(m=>m.default.hash('moviebenit@1',12).then(console.log))"
INSERT INTO users (full_name, email, password_hash, role)
VALUES (
  'Isaac Benit',
  'isaac.benit@testsolutions.de',
  '$2b$12$placeholder_run_fix_admin_hash_script_to_set_real_hash',
  'Admin'
)
ON CONFLICT (email) DO NOTHING;

-- Seed exactly 2 rooms (idempotent)
INSERT INTO rooms (name, description)
VALUES
  ('Business Class Room', 'Executive boardroom, seats 12, full AV setup'),
  ('Ground Floor Operations Room', 'Operations hub, open layout, seats 20')
ON CONFLICT (name) DO NOTHING;

COMMIT;
